### ISSUE TITLE
zsh git plugin alias

### ISSUE THREAD

**Issue by djkloop** [stefanmaric/g#10]
[~]$ command -v g
alias g=git

// Conflict with git plugin alias in zsh

**Comment by JoseAlban** [comment]
Calling it `g` was a bold move, but many devs will have `g` aliased to `git` or something else.
Would you mind renaming it to more chars? maybe `gv` ?

**Comment by stefanmaric** [comment]
Hi everyone! Thanks for your interest and raising your concern.

I'll be adding a feature to `g-install` to help the user setup an alias for this tool if it detects `g` is already an alias on the selected shell, as it will definitely be in `zsh` if `oh-my-zsh` is used.

In the meantime, you can easily workaround this conflict by setting up an alias [as I described in another issue](https://github.com/stefanmaric/g/issues/4#issuecomment-465688153):

```shell
alias -s ggo="$GOPATH/bin/g"
```

I'm quite in love with `g`'s name so will avoid a rename for now. 😅

If you're interested, you can check the upcoming changes for `g`, like posix compliance and bugfixes for edge cases at [the `next` branch](https://github.com/stefanmaric/g/compare/next) and you can watch for releases to get notified when the alias feature gets out.

I will this issue open until then to keep track.

**Comment by alvinmatias69** [comment]
Hi, I'm interested in these issues. Can I open a PR to automatically add alias on conflict `g`?

**Comment by stefanmaric** [comment]
Hi!

> . Can I open a PR to automatically add alias on conflict `g`?

Thanks for your interest. :heart: 

I have already some preliminary work ready for it, but I'm open to PRs since I'm traveling right now so won't be pushing it soon.

In case you want to try, it has to be done for the other shells as well, to give them feature parity and not discriminate — at least for `bash` and `fish` initially since those are the popular ones along with `zsh`.

You will need to implement 2 functions similar to the `get_line_for_shell`/`get_dotfile_for_shell` functions, one to determine whenever or not a `g` alias exists on that given shell (usually by something like `sh -i -c 'alias'` but it it's shell dependent) and one to construct a configuration command (again, shell dependent) to be put in the shell initialization file (I decided g-install is going to set a line per feature (env vars, aliases, completions, etc)).

It should warn the user about the conflict and offer to add an alias, allowing the user to choose a name or use a default which I think should be `ggovm` (g Go Version Manager) (verbose enough to prevent another accidental conflict on the users' system) — the user should be allowed to skip the alias setup entirely as well. (this means 2 prompts, a yes/no to start the setup and another one to choose the name).

So those would be the general guidelines. It can be polished further if a PR gets open.

And of course, please refer to the [license](https://github.com/stefanmaric/g/blob/master/LICENSE) and the [contributing guidelines](https://github.com/stefanmaric/g/blob/master/CONTRIBUTING.md). :heart:

**Comment by alvinmatias69** [comment]
Hi, I'm sorry it's taking way longer than I thought. Please let me know what you think of the PR. Thanks :heart:

**Comment by stefanmaric** [comment]
Addressed in #12 

It will go out in next release.
