### ISSUE TITLE
ERROR: $GOPATH and $GOROOT environment variables are required.

### ISSUE THREAD

**Issue by Kroning** [stefanmaric/g#37]
Running any "g" command gives error:
ERROR: $GOPATH and $GOROOT environment variables are required.

But
#go env | grep "GOR\|GOPA"
GOPATH="/home/kroning/go"
GOROOT="/usr/lib/go-1.18"

Ubuntu 22.04

**Comment by stefanmaric** [comment]
Hi @Kroning 

It looks like you have an existing installation of go. [I recommend to remove previous installations of go](https://github.com/stefanmaric/g/blob/next/README.md#requirements) specially to avoid confusions. Those variables print by your system installation are probably go's fallback and not really set (at least not in that shell session).

Regardless, did you install g via [the g-install script](https://github.com/stefanmaric/g/blob/next/README.md#single-line-installation)?

If you did, make sure to restart your shell session.

If not, you have to make sure you manually set those env vars in your shell config, as noted in the [manual installation steps](https://github.com/stefanmaric/g/blob/next/README.md#manual-installation).

I'm going to close this issue because it is missing context for me to better help you troubleshoot. If my recommendations above didn't help, please open a new issue using [the bug report template](https://github.com/stefanmaric/g/issues/new?template=bug_report.md).
