### ISSUE TITLE
Naming of the tool

### ISSUE THREAD

**Issue by AuHau** [stefanmaric/g#4]
Thanks for the nice tool that support `fish`! Yey!

Just small feedback on the naming of the tool. Single character naming is I think not very fortunate because it might collide with user's aliases or some other utilities. In this case, I have a conflict with git aliases (https://github.com/simnalamburt/cgitc) and I can imagine there will be quiet some people who might have same problem.

Do you know if simply renaming the installed binary will break things or not?

**Comment by stefanmaric** [comment]
Hi!

Definitely the shorter the name, the more susceptible to collisions! Before publishing, I looked around and didn't find common commands called `g` (looked on ubuntu's repos), but this issue popped up quite soon. :smile: 

> Do you know if simply renaming the installed binary will break things or not?

Renaming it will indeed break some features, like the `self-upgrade` feature. But using an alias on your shell should be pretty safe. For example, on fishshell:

```shell
alias -s ggo="$GOPATH/bin/g"
```

Since aliases in general take precedence over the `PATH`, you should be able to keep using `cgitc`s `g` alias without trouble.

Let me know if that helps.

**Comment by AuHau** [comment]
Oh right, it did not cross my mind to alias absolute path. That will definitely solve the problem and will be a definitely cleaner solution. Thanks!

**Comment by stefanmaric** [comment]
Glad to help!

**Comment by doubledgedboard** [comment]
Just wanted to drop in and say I found this tool previously, and it was extremely hard to find it again due to the overly short name.

It took multiple searches, what finally worked was `gvm golang "g"` at which point it was like the 3rd or 4th result down

any other tool with an at least somewhat unique or searchable name can usually be found in the top result with the right search

**Comment by stefanmaric** [comment]
Hi @doubledgedboard, thanks for chiming in!

I'm curious: if you put "go version manager" on Google, doesn't `g` appear as one of the first few results?

Asking because I get it as the second result, logged in and in private mode.

I also get it as the 6th result in GitHub if I search for "go version manager".

What were your initial search terms? So I can add content and tags related to it.
