### ISSUE TITLE
[question] ls as an alias `g list-all`

### ISSUE THREAD

**Issue by detj** [stefanmaric/g#6]
It would be great to keep the usage of `g` similar to `n`. For example, `n ls` lists all the available node versions, but the corresponding command in `g` is `g list-all`. Is there any reason why ?

**Comment by stefanmaric** [comment]
Hi!

Thanks for bringing this up.

The thing is that there are two kinds of lists, the list of locally installed versions and the list of all "remote" versions. I wanted to split these two because sometimes one might want to pipe these commands to get info about the current state of the system. Also I think it should be offline-first.

Because of this it is a bit ambiguous whenever `ls` means `list` or `list-all`.

I guess I might have used a flag instead; `g list-all` -> `g list --all`, but that doesn't address this concern and it is a bit harder to implement.

I'm particularly against of 2 slightly diff ways of achieving the exact same thing. But I'm open to a PR to add aliases. Maybe `ls` for `list` and `la` for `list-all` (since `la` is a very common alias for `ls --all`).

I understand familiarity is an important point for a good UX, but I don't think it really has to match `n` since it is not a standard util and actually `nvm` is the most popular node version manager (even tho I'm certain `n` is far superior), which uses `list` and `list-remote` respectively.

Random note: I named it `list-all` instead of `list-remote` or something similar because that command also informs you about which of all those versions you have installed already.

**Comment by detj** [comment]
@stefanmaric And thanks for the amazing answer. Not able to pipe output of one Unix command to another is disappointing, I've felt that with arbitrarily built commands so many times. Exactly, the kind of reasons I was looking for.

> even tho I'm certain `n` is far superior

Totally! 😄 

I'll see if I can cook up aliases in a PR. Thanks again.
