### ISSUE TITLE
Suggestion: Add a command to be able to switch between installed go versions

### ISSUE THREAD

**Issue by RobertYost** [stefanmaric/g#8]
[n](https://github.com/tj/n) let's you switch between the different versions you have installed by running `n <version>` - it would be nice if there was a similar ability here. Or if there is already, how do you do so? There's `g run <version>` but that does not seem to be persistent.

**Comment by stefanmaric** [comment]
Hi @RobertYost , `g install <version>` doubles as switcher if the version is installed already; it is a single command.

You can also run `g` without arguments to launch the interactive mode.

I guess I messed up a bit with the naming, I might have used `use` instead of `install` or something. :thinking:

**Comment by RobertYost** [comment]
@stefanmaric ah I see, thanks for pointing that out! I will close this issue then, wasn't aware of that

**Comment by stefanmaric** [comment]
@RobertYost fyi, I might be changing it soon, added some items to my TODO in the `next` branch: https://github.com/stefanmaric/g/commit/72a70406f7a2b1fcc545b17ea27265b40373085a

I will take the freedom to break some stuff while `g` is in pre `v1` state. :smile: 

Thanks for taking your time to chime in. <3
