### ISSUE TITLE
Homebrew install

### ISSUE THREAD

**Issue by brunowego** [stefanmaric/g#9]
Hi @stefanmaric, go to the masses, add brew! :)

```sh
brew install g
```

**Comment by stefanmaric** [comment]
Hey @brunowego, thanks for passing by!

Interesting proposition. I'm not a regular Mac user: does adding an app as a brew formula provide discoverability benefits?

I ask because to me doing `brew install g` offers pretty much the same friction as `curl -sSL https://git.io/g-install | bash`. So easy of use is not a seller point. Discoverability is, but I haven't ever browsed formulas without knowing what I'm looking for.

Adding a formula for `g` should be pretty easy. I'm planning to do a few small breaking changes before pining `v1.0.0`. Afterwards seems a good time in case it is necessary.

Let me know your thoughts.<3

**Comment by brunowego** [comment]
I fully agree with you. This proposal is just another way to make the package available! Thanks a lot! :)
